# Generated by Django 5.1.4 on 2024-12-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_centralgood_centralpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='centralgood',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='eastgood',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='northgood',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='southgood',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='westgood',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
