# Generated by Django 5.1.4 on 2024-12-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_centralgood_description_eastgood_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centralgood',
            name='name',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='eastgood',
            name='name',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='northgood',
            name='name',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='southgood',
            name='name',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='westgood',
            name='name',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
    ]
