name: Pylint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: 运行 Pylint
        run: pylint app/ myapp/
